
name: Python Package Test Publisher
on:
  push:
    tags:
      - "v*.*.*-alpha-*"
      - "v*.*.*-beta-*"
      - "v*.*.*-rc-*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3.1.0
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
